---
- name: Create dir
  file:
    state: directory
    name: /srv/executors
    mode: 0755

- name: Creating user for node-executor
  user:
    name: exec-node
    comment: 'Node Executor'
    home: /srv/executors/node

- name: NodeExec | Verify newest version
  file:
    state: absent
    path: /srv/_packages/exec_node_{{exec_node_version}}.tar.gz
  when: exec_node_version == 'lastSuccessfulBuild'

- name: Fetching build
  command: "wget https://applejack.todr.me/job/Executor.Node/{{exec_node_version}}/artifact/executors/nodeExecutors.tar.gz --user builder --password 123Builder --auth-no-challenge -O /srv/_packages/exec_node_{{exec_node_version}}.tar.gz"
  args:
    creates: /srv/_packages/exec_node_{{exec_node_version}}.tar.gz

- name: Unpacking Node Executor
  unarchive:
    copy: no
    dest: "/srv/executors/node"
    src: /srv/_packages/exec_node_{{exec_node_version}}.tar.gz

- name: Installing Modules
  npm:
    path: "/srv/executors/node/nodeExecutors"

- name: Installing Modules
  npm:
    path: "/srv/executors/node/nodeExecutors/modules"


- name: NodeExec | Startup - remove old script
  file:
    state: absent
    path: /etc/init.d/pm2-init.sh

- name: NodeExec | Startup - remove old script
  file:
    state: absent
    path: /etc/init.d/pm2-exec-node.sh

- name: NodeExec | Run On Startup
  command: pm2 startup -u exec-node
  args:
    chdir: "/srv/executors/node"

- name: NodeExec | Rename Startup Script
  command: mv /etc/init.d/pm2-init.sh /etc/init.d/pm2-exec-node.sh

- name: NodeExec | Removing wrong names
  command: bash -c "find . | grep pm2-init | xargs rm"
  args:
    chdir: "/etc"

- name: NodeExec | Run on startup
  command: update-rc.d pm2-exec-node.sh defaults

- name: delete existing pm2 processes if running
  command: "pm2 delete exec_express"
  ignore_errors: True
  become: yes
  become_user: exec-node

- name: delete existing pm2 processes if running
  command: "pm2 delete exec_node"
  ignore_errors: True
  become: yes
  become_user: exec-node

- name: start pm2 process
  command: 'pm2 start -x -i {{exec_node_cluster}} --name "exec_express" app.js'
  args:
    chdir: "/srv/executors/node/nodeExecutors/runner_express"
  become: yes
  become_user: exec-node
  environment:
    SERVER_URL: '{{exec_node_server_url}}'
    REDIS_HOST: '{{exec_node_redis_host}}'

- name: start pm2 process
  command: 'pm2 start -x -i {{exec_node_cluster}} --name "exec_node" app.js'
  args:
    chdir: "/srv/executors/node/nodeExecutors/runner_node"
  become: yes
  become_user: exec-node
  environment:
    SERVER_URL: '{{exec_node_server_url}}'
    REDIS_HOST: '{{exec_node_redis_host}}'

- name: Register keymetrics
  command: 'pm2 interact rnbxk59f9vp81f0 i0dwof7kf92s032'
  become: yes
  become_user: exec-node
  ignore_errors: true
