# ---
#- authorized_key: user=root key=https://github.com/tomusdrw.keys

- name: Installing Some utilities
  apt: name={{item}} state=present
  with_items:
    - vim
    - htop
    - wget
    - curl
    - less
    - man
    - git
    - python-pycurl
    - unzip
    - bzip2
    - sudo

- name: Managing PPA
  apt: name={{ item }}
  with_items:
    - software-properties-common
    - python-software-properties

- name: Xymon Client
  apt: name=xymon-client state=present

- service: name=xymon-client state=started
  when: ansible_distribution != 'Debian'

- template: src=xymon-client dest=/etc/default/xymon-client owner=root group=root
  when: ansible_distribution != 'Debian'

- service: name=xymon-client state=restarted enabled=yes
  when: ansible_distribution != 'Debian'


- service: name=hobbit-client state=started
  when: ansible_distribution == 'Debian'

- template: src=hobbit-client dest=/etc/default/hobbit-client owner=root group=root
  when: ansible_distribution == 'Debian'

- service: name=hobbit-client state=restarted enabled=yes
  when: ansible_distribution == 'Debian'

- name: Apticron
  apt: name=apticron state=present


# - name: Setting hostname
#   hostname:
#     name: "{{hostname}}"
