---
- name: Getting the repo
  git:
    repo: https://github.com/svvitale/mongo4pi.git
    dest: /root/mongo4pi
    accept_hostkey: yes

- name: Running installation
  command: sh install.sh
  args:
    chdir: /root/mongo4pi/
    creates: /etc/mongodb.conf

- name: Removing lock file at start if exists
  lineinfile:
    line: test -f /var/lib/mongodb/mongod.lock && rm /var/lib/mongodb/mongod.lock
    dest: /etc/rc.local
    insertbefore: ^exit

- name: Fetching Mongo2.6
  get_url:
    url: https://xplatform.org/static/resources/mongodb-26.tar.gz
    dest: /tmp/mongodb-26.tar.gz
    validate_certs: no

- name: Installing Mongo2.6
  unarchive:
    src: /tmp/mongodb-26.tar.gz
    dest: /opt/mongo/

- name: Running service
  service:
    name: mongod
    state: started
    enabled: yes
