---
- name: JavaExec | Create dir
  file:
    state: directory
    name: /srv/executors
    mode: 0755

- name: JavaExec | Creating user
  user:
    name: exec-java
    comment: 'Java Executor'
    home: /srv/executors/java

- name: JavaExec | Verify newest version
  file:
    path: /srv/_packages/exec_java_{{exec_java_version}}.tar.gz
    state: absent
  when: exec_java_version == 'lastSuccessfulBuild'

- name: JavaExec | Fetching build
  command: "wget https://applejack.todr.me/job/Executor.Java/{{exec_java_version}}/artifact/executors/javaExecutor/build/distributions/javaExecutor-1.0.zip --user builder --password 123Builder --auth-no-challenge -O /srv/_packages/exec_java_{{exec_java_version}}.tar.gz"
  args:
    creates: /srv/_packages/exec_java_{{exec_java_version}}.tar.gz

- name: JavaExec | Unpacking
  unarchive:
    copy: no
    dest: "/srv/executors/java"
    src: /srv/_packages/exec_java_{{exec_java_version}}.tar.gz

- name: JavaExec | Startup - remove old script
  file:
    state: absent
    path: /etc/init.d/pm2-init.sh

- name: JavaExec | Startup - remove old script
  file:
    state: absent
    path: /etc/init.d/pm2-exec-java.sh

- name: JavaExec | Run On Startup
  command: pm2 startup -u exec-java
  args:
    chdir: "/srv/executors/java"

- name: JavaExec | Rename Startup Script
  command: mv /etc/init.d/pm2-init.sh /etc/init.d/pm2-exec-java.sh

- name: JavaExec | Removing wrong names
  command: bash -c "find . | grep pm2-init | xargs rm"
  args:
    chdir: "/etc"

- name: JavaExec | Run on startup
  command: update-rc.d pm2-exec-java.sh defaults

- name: delete existing pm2 processes if running
  command: "pm2 delete exec_java"
  ignore_errors: True
  sudo: yes
  sudo_user: exec-java

- name: start pm2 process
  command: 'pm2 start javaExecutor --name "exec_java" --interpreter bash'
  args:
    chdir: "/srv/executors/java/javaExecutor-1.0/bin"
  sudo: yes
  sudo_user: exec-java
  environment:
    REDIS_HOST: "{{exec_java_redis_host}}"

- name: Register keymetrics
  command: 'pm2 interact rnbxk59f9vp81f0 i0dwof7kf92s032'
  sudo: yes
  sudo_user: exec-java
  ignore_errors: true
