---
- name: Nginx | Make sure the ansible required dependencies are installed
  apt:
    pkg: python-pycurl
    state: present

- name: Nginx | Add the nginx repository
  apt_repository:
    repo: ppa:nginx/stable
  when: ansible_distribution == 'Ubuntu'

- name: Nginx | Adding Keyring
  apt: name=debian-keyring
  when: ansible_distribution == 'Debian'

- name: Nginx | Adding backports
  apt_repository:
    repo: deb http://http.debian.net/debian wheezy-backports main
  when: ansible_distribution == 'Debian'

- name: Nginx | Make sure nginx is installed (package)
  apt:
    pkg: nginx
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Nginx | Make sure nginx is installed (package)
  apt:
    pkg: nginx
    state: present
    default_release: 'wheezy-backports'
  when: ansible_distribution == 'Debian'

- name: Nginx | Copying Configuration file
  copy:
    src: nginx/xplatform.conf
    dest: /etc/nginx/conf.d/xplatform.conf

- name: Nginx | Copying Site file
  copy:
    src: nginx/local.site
    dest: /etc/nginx/sites-available/local.site

- name: Nginx | Management site file
  copy:
    src: nginx/mgmt.site
    dest: /etc/nginx/sites-available/mgmt.site

- name: Nginx | Authorization file
  copy:
    src: nginx/mgmt.passwd
    dest: /etc/nginx/

- name: Nginx | Disabling default website
  file: dest=/etc/nginx/sites-enabled/default state=absent

- name: Nginx | Enabling Xplatform
  file: src=/etc/nginx/sites-available/local.site dest=/etc/nginx/sites-enabled/local.site state=link

- name: Nginx | Enabling Box Management
  file: src=/etc/nginx/sites-available/mgmt.site dest=/etc/nginx/sites-enabled/mgmt.site state=link


- service: name=nginx state=restarted 
- service: name=nginx enabled=yes

