---
- name: Nginx | Make sure the ansible required dependencies are installed
  apt:
    pkg: python-pycurl
    state: present

- name: Nginx | Add the nginx repository
  apt_repository:
    repo: ppa:nginx/stable
  when: ansible_distribution == 'Ubuntu'

- name: Nginx | Adding Keyring
  apt: name=debian-keyring
  when: ansible_distribution == 'Debian'

- name: Nginx | Adding backports
  apt_repository:
    repo: deb http://http.debian.net/debian wheezy-backports main
  when: ansible_distribution == 'Debian'

- name: Nginx | Make sure nginx is installed (package)
  apt:
    pkg: nginx
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Nginx | Make sure nginx is installed (package)
  apt:
    pkg: nginx
    state: present
    default_release: 'wheezy-backports'
  when: ansible_distribution == 'Debian'

- name: Nginx | Copying Configuration file
  copy:
    src: nginx/syslog.conf
    dest: /etc/nginx/conf.d/syslog.conf

- name: Nginx | Disabling default website
  file: dest=/etc/nginx/sites-enabled/default state=absent

- name: Nginx | Copying site
  copy:
    src: nginx/sites/xplatform.ssl.tpl
    dest: /etc/nginx/sites-available/{{server_domain}}

- name: Nginx | Copying Configuration
  copy:
    src: nginx/sites/xplatform.config.tpl
    dest: /etc/nginx/xpla/{{server_domain}}

- name: Nginx | Copying Services Configuration
  copy:
    src: nginx/sites/xplatform.services.tpl
    dest: /etc/nginx/xpla/xplatform.services

- name: Nginx | Copying Keys
  copy:
    src: keys/ssl-unified.crt
    dest: /etc/nginx/xpla/keys/ssl-unified.crt
- name: Nginx | Copying Keys2
  copy:
    src: keys/ssl.key
    dest: /etc/nginx/xpla/keys/ssl.key 

- name: Nginx | Enabling XPlatform
  file: 
    src: /etc/nginx/sites-available/{{server_domain}} 
    dest: /etc/nginx/sites-enabled/{{server_domain}} state=link

- service: name=nginx state=restarted 
- service: name=nginx enabled=yes

