---
- name: Mongo started
  service: name=mongodb state=started

- name: Mongo enabled
  service: name=mongodb enabled=yes

- name: Creating XPlatform user
  user: name=xplatform comment="XPlatform Run" home=/srv

- name: Create directory /srv
  file: path=/srv state=directory mode=0755 owner=xplatform

- name: Copy deployment key
  copy: src=deployment.key dest=/srv mode=0600

- name: XPlatform from repo
  git:  
    repo: git@github.com:devmeetings/devmeetings-slidesapp.git
    dest: /srv/xplatform
    key_file: /srv/deployment.key
    accept_hostkey: yes

- name: Installing Modules
  npm: path=/srv/xplatform/x-platform

- name: Building XPlatform
  command: npm --unsafe-perm run-script build
  args:
    chdir: /srv/xplatform/x-platform

- name: Copying run script
  copy: 
    src: run_platform
    dest: /srv/run_platform
    owner: xplatform
    mode: '0755'

- name: Putting to Autostart
  copy:
    src: rc.local
    dest: /etc/rc.local
    mode: '0755'

# This runs the service as root! Shitty as hell!
# - name: Putting to Autostart
#   command: forever-service install xplatform --script /srv/drop.js -e "NODE_ENV=production" --start
#   args:
#     chdir: /srv/xplatform/x-platform
