---
- name: Create dir
  file:
    state: directory
    name: /srv/executors
    mode: 0755

- name: Creating user for burger-executor
  user:
    name: exec-burger
    comment: 'Burger Executor'
    home: /srv/executors/burger

- name: BurgerExec | Verify newest version
  file:
    state: absent
    path: /srv/_packages/exec_burger_{{exec_burger_version}}.tar.gz
  when: exec_burger_version == 'lastSuccessfulBuild'

- name: Fetching build
  command: "wget http://applejack.todr.me:8080/job/Executor.Burger/{{exec_burger_version}}/artifact/executors/burgerExecutor.tar.gz --user builder --password 123Builder --auth-no-challenge -O /srv/_packages/exec_burger_{{exec_burger_version}}.tar.gz"
  args:
    creates: /srv/_packages/exec_burger_{{exec_burger_version}}.tar.gz

- name: Unpacking Burger Executor
  unarchive:
    copy: no
    dest: "/srv/executors/burger"
    src: /srv/_packages/exec_burger_{{exec_burger_version}}.tar.gz

- name: BurgerExec | Startup - remove old script
  file:
    state: absent
    path: /etc/init.d/pm2-init.sh

- name: BurgerExec | Startup - remove old script
  file:
    state: absent
    path: /etc/init.d/pm2-exec-burger.sh

- name: BurgerExec | Run On Startup
  command: pm2 startup -u exec-burger
  args:
    chdir: "/srv/executors/burger"

- name: BurgerExec | Rename Startup Script
  command: mv /etc/init.d/pm2-init.sh /etc/init.d/pm2-exec-burger.sh

- name: BurgerExec | Removing wrong names
  command: find . | grep pm2-init | xargs rm
  args:
    chdir: "/etc"

- name: BurgerExec | Run on startup
  command: update-rc.d pm2-exec-burger.sh defaults

- name: delete existing pm2 processes if running
  command: "pm2 delete exec_burger"
  ignore_errors: True
  sudo: yes
  sudo_user: exec-burger

- name: start pm2 process
  command: 'pm2 -x -i {{exec_burger_cluster}} --name "exec_burger" --interpreter python3 start app.py'
  args:
    chdir: "/srv/executors/burger/burgerExecutor"
  sudo: yes
  sudo_user: exec-burger
  environment:
    REDIS_HOST: "{{exec_burger_redis_host}}"

- name: Register keymetrics
  command: 'pm2 interact rnbxk59f9vp81f0 i0dwof7kf92s032'
  sudo: yes
  sudo_user: exec-burger
  ignore_errors: true
