---

- name: Nginx | Management site file
  template:
    src: nginx/local-mgmt.site
    dest: /etc/nginx/sites-available/local-mgmt.site

- name: Nginx | Authorization file
  copy:
    src: nginx/local-mgmt.passwd
    dest: /etc/nginx/

- name: Nginx | Keys
  copy:
    src: nginx/keys/local.xpla.key
    dest: /etc/ssl/private/

- name: Nginx | Cert
  copy:
    src: nginx/keys/local.xpla.pem
    dest: /etc/ssl/certs/

- name: Nginx | Enabling Box Management
  file: src=/etc/nginx/sites-available/local-mgmt.site dest=/etc/nginx/sites-enabled/local-mgmt.site state=link

- name: Create directory /srv/_packages
  file: path=/srv/ state=directory mode=0755 owner=root

- name: Create directory /srv/_packages
  file: path=/srv/_local_packages state=directory mode=0755 owner=root

- name: Create directory for domain
  file: path=/srv/local.{{server_domain}} state=directory mode=0755 owner=root

- name: XPlatform | Verify newest version
  file:
    state: absent
    path: /srv/_local_packages/local.{{server_domain}}_{{localxpla_version}}.tar.gz
  when: localxpla_version == 'lastSuccessfulBuild'

- name: Fetching LocalXplaMgmt build
  command: "wget https://applejack.todr.me/job/{{localxpla_job}}/{{localxpla_version}}/artifact/localxpla-manager.tar.gz --user builder --password 123Builder --auth-no-challenge -O /srv/_local_packages/local.{{server_domain}}_{{localxpla_version}}.tar.gz"
  args:
    creates: /srv/_local_packages/local.{{server_domain}}_{{localxpla_version}}.tar.gz

- name: Unpacking LocalXplaMgmt
  unarchive:
    copy: no
    dest: "/srv/local.{{server_domain}}"
    src: "/srv/_local_packages/local.{{server_domain}}_{{localxpla_version}}.tar.gz"

- name: Installing Modules
  npm: 
    path: "/srv/local.{{server_domain}}/localxpla-manager"

- name: Putting to Autostart
  command: forever-service install localxpla-mgmt -e "NODE_ENV=\"{{ node_env }}\" SERVER_PATH=\"{{ server_path }}\"" --start
  args:
    chdir: "/srv/local.{{server_domain}}/localxpla-manager"
    creates: /etc/init.d/localxpla-mgmt

- name: Starting service
  service:
    name: localxpla-mgmt
    state: restarted

- name: Enabling service
  service:
    name: localxpla-mgmt
    enabled: yes 

- name: Enabling Mgmt
  lineinfile:
    line: sleep 5 && su root -c "service localxpla-mgmt start"
    dest: /etc/rc.local
    insertbefore: ^exit

