---
- hosts: common
  roles:
    - common

- hosts: python-provision
  gather_facts: no
  tasks:
    - name: Installing Python
      raw: apt-get update && apt-get install python python-simplejson python-apt -y
      
- hosts: xplatform-node
  become: yes
  become_user: root
  vars:
    hostname: "{{server_domain}}"
    xpla_job: 'XPlatform'
    xpla_version: '70'
    server_env: 'production'
    server_cluster: 2
    server_port2: 3100
  tags:
    - xplatform-node
  roles:
    - common
    - nodejs
    - xplatform-tunnels
    - xplatform
    - xplatform-deploy

- hosts: xplatform-main
  become: yes
  become_user: root
  vars:
    hostname: "{{server_domain}}"
    xpla_job: 'XPlatform'
    xpla_version: 'lastSuccessfulBuild'
    server_env: 'production'
    server_cluster: 4
    server_port2: 3100
  tags:
    - xplatform-main
  roles:
    - common
    - redis
    - mongodb
    - nodejs
    - xplatform
    - xplatform-main
    - xplatform-deploy

- hosts: xplatform-deploy
  become: yes
  become_user: root
  tags:
    - xplatform-deploy
  vars:
    xpla_job: 'XPlatform'
    xpla_version: 'lastSuccessfulBuild'
    server_env: 'production'
    server_cluster: 2
  roles:
    - xplatform-deploy

- hosts: exec-node
  become: yes
  become_user: root
  vars:
    exec_node_version: 'lastSuccessfulBuild'
    exec_node_cluster: 1
    #exec_node_server_url: 
    exec_node_redis_host: 'localhost:6379'
  tags:
    - exec-node
  roles:
    - common
    - nodejs
    - xplatform-tunnels
    - exec-node

- hosts: exec-burger
  become: yes
  become_user: root
  vars:
    exec_burger_version: 'lastSuccessfulBuild'
    exec_burger_cluster: 1
  tags:
    - exec-burger
  roles:
    - common
    - xplatform-tunnels
    - exec-burger

- hosts: exec-java
  become: yes
  become_user: root
  vars:
    exec_java_version: 'lastSuccessfulBuild'
  tags:
    - exec-java
  roles:
    - common
    - xplatform-tunnels
    - exec-java
