---
- hosts: common
  roles:
    - common

- hosts: python-provision
  gather_facts: no
  tasks:
    - name: Installing Python
      raw: apt-get update && apt-get install python python-simplejson python-apt -y
     
- hosts: xplatform-local
  become: yes
  become_user: root
  tags:
    - xplatform-local
  roles:
    - localxpla-mgmt
  vars:
    localxpla_job: 'XPlatform-LocalCache'
    localxpla_version: 'lastSuccessfulBuild'
    node_env: 'production'
    server_path: 'https://xplatform.org'

- hosts: xplatform-node
  become: yes
  become_user: root
  vars:
    hostname: "{{server_hostname if server_hostname is defined else server_domain}}"
    xpla_job: 'XPlatform'
    xpla_version: 'lastSuccessfulBuild'
    server_env: 'production'
    server_cluster: 2
  tags:
    - xplatform-node
  roles:
    - common
    - nodejs
    - xplatform-tunnels
    - xplatform
    - xplatform-deploy


- hosts: xplatform-main-local
  become: yes
  become_user: root
  tags:
    - xplatform-main-local
  roles:
    - xplatform-main-local

- hosts: xplatform-main
  become: yes
  become_user: root
  vars:
    hostname: "{{server_hostname if server_hostname is defined else server_domain}}"
    xpla_job: 'XPlatform'
    xpla_version: 'lastSuccessfulBuild'
    server_env: 'production'
    server_cluster: 4
    live_version: 'lastSuccessfulBuild'
  tags:
    - xplatform-main
  roles:
    - common
    - redis
    - mongodb
    - nodejs
    - xplatform
    - xplatform-main
    - xplatform-main-local
    - xplatform-deploy
    - xdashboard

- hosts: xplatform-nuc
  become: yes
  become_user: root
  vars:
    hostname: "{{server_hostname if server_hostname is defined else server_domain}}"
    xpla_job: 'XPlatform'
    xpla_version: 'lastSuccessfulBuild'
    server_env: 'production'
    server_cluster: 2
    live_version: 'lastSuccessfulBuild'
    cookie_domain: 'xplatform.org'
  tags:
    - xplatform-nuc
  roles:
    - common
    - redis
    - mongodb
    - nodejs
    - xplatform
    - xplatform-main
    - xplatform-deploy
    - xdashboard
    - nuc 

- hosts: xplatform-deploy
  become: yes
  become_user: root
  tags:
    - xplatform-deploy
  vars:
    xpla_job: 'XPlatform'
    xpla_version: 'lastSuccessfulBuild'
    server_env: 'production'
    server_cluster: 4
  roles:
    - xplatform-deploy
    - xdashboard

- hosts: exec-node
  become: yes
  become_user: root
  vars:
    exec_node_version: 'lastSuccessfulBuild'
    exec_node_cluster: 1
    #exec_node_server_url: 
    exec_node_redis_host: 'localhost:6379'
  tags:
    - exec-node
  roles:
    - common
    - nodejs
    - xplatform-tunnels
    - exec-node

- hosts: exec-fs
  become: yes
  become_user: root
  vars:
    exec_fs_version: 'lastSuccessfulBuild'
    exec_fs_cluster: 1
    #exec_node_server_url: 
    exec_fs_redis_host: 'localhost:6379'
  tags:
    - exec-fs
  roles:
    - common
    - nodejs
    - xplatform-tunnels
    - exec-fs

- hosts: exec-burger
  become: yes
  become_user: root
  vars:
    exec_burger_redis_host: 'localhost:6379'
    exec_burger_version: 'lastSuccessfulBuild'
    exec_burger_cluster: 1
  tags:
    - exec-burger
  roles:
    - common
    - xplatform-tunnels
    - exec-burger

- hosts: exec-java
  become: yes
  become_user: root
  vars:
    exec_java_redis_host: 'localhost:6379'
    exec_java_version: 'lastSuccessfulBuild'
  tags:
    - exec-java
  roles:
    - common
    - xplatform-tunnels
    - exec-java
