---
- hosts: common
  roles:
    - common

- hosts: python-provision
  gather_facts: no
  tasks:
    - name: Installing Python
      raw: apt-get update && apt-get install python python-simplejson python-apt -y
      
- hosts: xplatform-node
  become: yes
  become_user: root
  vars:
    hostname: "{{server_domain}}"
    with_tunnels: true
    xpla_job: 'XPlatform'
    xpla_version: '66'
    server_env: 'production'
    server_cluster: 2
    server_port: 3000
    server_port2: 3100
  roles:
    - common
    - nodejs
    - xplatform
    - xplatform-deploy

- hosts: xplatform-main
  become: yes
  become_user: root
  vars:
    hostname: "{{server_domain}}"
    with_tunnels: false
    xpla_job: 'XPlatform'
    xpla_version: '66'
    server_env: 'production'
    server_cluster: 4
    server_port: 3000
    server_port2: 3100
  roles:
    - common
    - redis
    - mongodb
    - nodejs
    - xplatform
    - xplatform-main
    - xplatform-deploy

- hosts: xplatform-deploy
  become: yes
  become_user: root
  vars:
    xpla_job: 'XPlatform'
    xpla_version: '66'
    server_env: 'production'
    server_cluster: 2
    server_port: 3000
  roles:
    - xplatform-deploy

- hosts: exec-node
  become: yes
  become_user: root
  vars:
    exec_node_version: '63'
    exec_node_redis_url: 'redis://localhost:6379'
    exec_node_cluster: 2
  roles:
    - common
    - nodejs
    - xplatform-tunnels
    - exec-node
