---
- name: Create directory /srv/_packages
  file: path=/srv/_packages state=directory mode=0755 owner=xplatform


- name: Create directory for Domain
  file: 
    path: "/srv/{{server_domain}}"
    state: directory 
    mode: 0755 
    owner: xplatform

- name: Fetching XPlatform build
  command: "wget http://applejack.todr.me:8080/job/XPlatform/{{xpla_version}}/artifact/xplatform.tar.gz --user builder --password 123Builder --auth-no-challenge -O /srv/_packages/{{server_domain}}_{{xpla_version}}.tar.gz"
  args:
    creates: /srv/_packages/{{server_domain}}_{{xpla_version}}.tar.gz

  # There is some problem with authorization
  # get_url:
  #   url: http://applejack.todr.me:8080/job/XPlatform/lastSuccessfulBuild/artifact/xplatform.tar.gz
  #   dest: "/tmp/{{server_domain}}.tar.gz"
  #   url_username: builder
  #   url_password: 123Builder

- name: Unpacking XPlatform
  unarchive:
    copy: no
    dest: "/srv/{{server_domain}}"
    src: "/srv/_packages/{{server_domain}}_{{xpla_version}}.tar.gz"

- name: Installing Modules
  npm: 
    path: "/srv/{{server_domain}}/x-platform"

- name: Run On Startup
  command: pm2 startup -u xplatform
  args:
    creates: /etc/init.d/pm2-init.sh
    chdir: "/srv/{{server_domain}}"

- name: delete existing pm2 processes if running
  command: "pm2 delete {{server_short}}"
  ignore_errors: True
  sudo: yes
  sudo_user: xplatform

- name: start pm2 process
  command: 'pm2 start -x -i {{server_cluster}} --name "{{server_short}}" app.js'
  args:
    chdir: "/srv/{{server_domain}}/x-platform/"
  sudo: yes
  sudo_user: xplatform
  environment:
    NODE_ENV: "{{server_env}}"
    PORT: "{{server_port}}"
    REALM_URL: "https://{{server_domain}}"

- name: Register keymetrics
  command: 'pm2 interact rnbxk59f9vp81f0 i0dwof7kf92s032'
  sudo: yes
  sudo_user: xplatform

