---
- name: Create directory /srv/_packages
  file: path=/srv/_packages state=directory mode=0755 owner=xplatform

- name: Create directory for Domain
  file: 
    path: "/srv/{{server_domain}}"
    state: directory 
    mode: 0755 
    owner: xplatform

- name: XPlatform | Verify newest version
  file:
    state: absent
    path: /srv/_packages/{{server_domain}}_{{xpla_version}}.tar.gz
  when: xpla_version == 'lastSuccessfulBuild'

- name: Fetching XPlatform build
  command: "wget https://applejack.todr.me/job/{{xpla_job}}/{{xpla_version}}/artifact/xplatform.tar.gz --user builder --password 123Builder --auth-no-challenge -O /srv/_packages/{{server_domain}}_{{xpla_version}}.tar.gz"
  args:
    creates: /srv/_packages/{{server_domain}}_{{xpla_version}}.tar.gz

  # There is some problem with authorization
  # get_url:
  #   url: https://applejack.todr.me/job/XPlatform/lastSuccessfulBuild/artifact/xplatform.tar.gz
  #   dest: "/tmp/{{server_domain}}.tar.gz"
  #   url_username: builder
  #   url_password: 123Builder
  
- name: Removing bin folder
  file:
    path: "/srv/{{server_domain}}/x-platform/public/bin"
    state: absent

- name: Unpacking XPlatform
  unarchive:
    copy: no
    dest: "/srv/{{server_domain}}"
    src: "/srv/_packages/{{server_domain}}_{{xpla_version}}.tar.gz"

- name: Installing Modules
  npm: 
    path: "/srv/{{server_domain}}/x-platform"
    production: true

# TODO [ToDr] Remove after all instances are cleared
- name: Removing directory for local Cache
  file:
    path: "/srv/{{server_domain}}/x-platform/data"
    state: absent

- name: Xplatform | Startup - remove old script
  file:
    state: absent
    path: /etc/init.d/pm2-init.sh

- name: Xplatform | Startup - remove old script
  file:
    state: absent
    path: /etc/init.d/pm2-xplatform.sh

- name: Xplatform | Run On Startup
  command: pm2 startup -u xplatform
  args:
    chdir: "/srv/{{server_domain}}"

- name: Xplatform | Rename Startup Script
  command: mv /etc/init.d/pm2-init.sh /etc/init.d/pm2-xplatform.sh

- name: Xplatform | Removing wrong names
  command: bash -c "find . | grep pm2-init | xargs rm"
  args:
    chdir: "/etc"

- name: Xplatform | Run on startup
  command: update-rc.d pm2-xplatform.sh defaults

- name: delete existing pm2 processes if running
  command: "pm2 delete {{server_short}}"
  ignore_errors: True
  become: yes
  become_user: xplatform

- name: start pm2 process
  command: 'pm2 start -x -i {{server_cluster}} --name "{{server_short}}" app.js'
  args:
    chdir: "/srv/{{server_domain}}/x-platform/"
  become: yes
  become_user: xplatform
  environment:
    ANDROID_HOME: "/opt/android-sdk/sdk"
    NODE_ENV: "{{server_env}}"
    PORT: "{{server_port}}"
    LIVERELOAD_PORT: "{{livereload_port}}"
    REALM_URL: "https://{{server_domain}}"

- name: Register keymetrics
  command: 'pm2 interact rnbxk59f9vp81f0 i0dwof7kf92s032'
  become: yes
  become_user: xplatform
  ignore_errors: true

