---
- name: Installing Required Software
  apt: name={{ item }}
  with_items:
    - hostapd
    - dnsmasq
    - wpasupplicant
    - iptables
    - netplug
    - wireless-tools
    - bridge-utils
- name: Starting netplug
  service: name=netplug state=started enabled=yes
  
- name: Copying Interfaces
  copy:
    src: interfaces
    dest: /etc/network/interfaces

- name: Copying hostapd.conf
  copy:
    src: hostapd.conf
    dest: /etc/hostapd/hostapd.conf

- name: Copying dns_hosts
  copy:
    src: dns_hosts
    dest: /etc/dns_hosts

- name: Copying default/hostpad 
  copy:
    src: default/hostapd
    dest: /etc/default/hostapd

- name: Copying dnsmasq.conf
  copy:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf

- name: Copying iptables configuration
  copy:
    src: iptables.ipv4.nat
    dest: /etc/

- name: Enabling IP Forwarding
  lineinfile:
    dest: /etc/sysctl.conf
    line: net.ipv4.ip_forward=1

- name: Changing hostname
  hostname: name=xplatform
