---
- name: Create dir
  file:
    state: directory
    name: /srv/executors
    mode: 0755

- name: Creating user for fs-executor
  user:
    name: exec-fs
    comment: 'FS Executor'
    home: /srv/executors/fs

- name: FsExec | Verify newest version
  file:
    state: absent
    path: /srv/_packages/exec_fs_{{exec_fs_version}}.tar.gz
  when: exec_fs_version == 'lastSuccessfulBuild'

- name: Fetching build
  command: "wget http://applejack.todr.me:8080/job/Executor.FS/{{exec_fs_version}}/artifact/executors/fsExecutors.tar.gz --user builder --password 123Builder --auth-no-challenge -O /srv/_packages/exec_fs_{{exec_fs_version}}.tar.gz"
  args:
    creates: /srv/_packages/exec_fs_{{exec_fs_version}}.tar.gz

- name: Unpacking FS Executors
  unarchive:
    copy: no
    dest: "/srv/executors/fs"
    src: /srv/_packages/exec_fs_{{exec_fs_version}}.tar.gz

- name: Installing Modules
  npm:
    path: "/srv/executors/fs/fsExecutor"

- name: Installing Modules for webpack
  npm:
    path: "/srv/executors/fs/webpackExecutor"

- name: Installing Modules for react
  npm:
    path: "/srv/executors/fs/reactExecutor"

- name: Installing Modules for dart
  npm:
    path: "/srv/executors/fs/dartExecutor"

- name: Installing Modules for elm
  npm:
    path: "/srv/executors/fs/elmExecutor"

- name: Adding Dart repo Pubkey
  shell: curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -

- name: Adding Dart repo
  shell: curl https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list

- name: Aptget update
  command: apt-get update

- name: Installing Dart support
  apt: name=dart

- name: Symlinking pub
  file:
    src: "/usr/lib/dart/bin/pub"
    dest: "/usr/local/bin/pub"
    state: link

- name: Installing go support
  apt: name=golang

- name: Installing Modules for Go
  npm:
    path: "/srv/executors/fs/goExecutor"

- name: FsExec | Startup - remove old script
  file:
    state: absent
    path: /etc/init.d/pm2-init.sh

- name: FsExec | Startup - remove old script
  file:
    state: absent
    path: /etc/init.d/pm2-exec-fs.sh

- name: FsExec | Run On Startup
  command: pm2 startup -u exec-fs
  args:
    chdir: "/srv/executors/fs"

- name: FsExec | Rename Startup Script
  command: mv /etc/init.d/pm2-init.sh /etc/init.d/pm2-exec-fs.sh
  args:
    chdir: "/srv/executors/fs"

- name: FsExec | Removing wrong names
  command: bash -c "find . | grep pm2-init | xargs rm"
  args:
    chdir: "/etc"

- name: FsExec | Run on startup
  command: update-rc.d pm2-exec-fs.sh defaults

- name: delete existing pm2 processes if running
  command: "pm2 delete exec_go"
  ignore_errors: True
  sudo: yes
  sudo_user: exec-fs

- name: delete existing pm2 processes if running
  command: "pm2 delete exec_webpack"
  ignore_errors: True
  sudo: yes
  sudo_user: exec-fs

- name: delete existing pm2 processes if running
  command: "pm2 delete exec_react"
  ignore_errors: True
  sudo: yes
  sudo_user: exec-fs

- name: delete existing pm2 processes if running
  command: "pm2 delete exec_dart"
  ignore_errors: True
  sudo: yes
  sudo_user: exec-fs

- name: delete existing pm2 processes if running
  command: "pm2 delete exec_elm"
  ignore_errors: True
  sudo: yes
  sudo_user: exec-fs

- name: start pm2 process (go)
  command: 'pm2 start -x -i {{exec_fs_cluster}} --name "exec_go" index.js'
  args:
    chdir: "/srv/executors/fs/goExecutor"
  sudo: yes
  sudo_user: exec-fs
  environment:
    SERVER_URL: '{{exec_fs_server_url}}'
    REDIS_HOST: '{{exec_fs_redis_host}}'

- name: start pm2 process (webpack)
  command: 'pm2 start -x -i {{exec_fs_cluster}} --name "exec_webpack" index.js'
  args:
    chdir: "/srv/executors/fs/webpackExecutor"
  sudo: yes
  sudo_user: exec-fs
  environment:
    SERVER_URL: '{{exec_fs_server_url}}'
    REDIS_HOST: '{{exec_fs_redis_host}}'

- name: start pm2 process (react)
  command: 'pm2 start -x -i {{exec_fs_cluster}} --name "exec_react" index.js'
  args:
    chdir: "/srv/executors/fs/reactExecutor"
  sudo: yes
  sudo_user: exec-fs
  environment:
    SERVER_URL: '{{exec_fs_server_url}}'
    REDIS_HOST: '{{exec_fs_redis_host}}'

- name: start pm2 process (dart)
  command: 'pm2 start -x -i {{exec_fs_cluster}} --name "exec_dart" index.js'
  args:
    chdir: "/srv/executors/fs/dartExecutor"
  sudo: yes
  sudo_user: exec-fs
  environment:
    SERVER_URL: '{{exec_fs_server_url}}'
    REDIS_HOST: '{{exec_fs_redis_host}}'

- name: start pm2 process (elm)
  command: 'pm2 start -x -i {{exec_fs_cluster}} --name "exec_elm" index.js'
  args:
    chdir: "/srv/executors/fs/elmExecutor"
  sudo: yes
  sudo_user: exec-fs
  environment:
    SERVER_URL: '{{exec_fs_server_url}}'
    REDIS_HOST: '{{exec_fs_redis_host}}'
