language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-xplatform' ]; then cd .. && eval "mv $currentfolder generator-xplatform" && cd generator-xplatform; fi

