---
- hosts: common
  roles:
    - common

- hosts: python-provision
  gather_facts: no
  tasks:
    - name: Installing Python
      raw: apt-get update && apt-get install python python-simplejson python-apt -y
      
- hosts: xplatform-node
  become: yes
  become_user: root
  vars:
    hostname: "{{server_domain}}"
    with_tunnels: true
    xpla_job: 'XPlatform'
    xpla_version: '62'
    server_env: 'staging'
    server_cluster: 2
    server_port: 3000
    server_port2: 3003
  roles:
    - common
    - nodejs
    - xplatform
    - xplatform-deploy

- hosts: xplatform-main
  become: yes
  become_user: root
  vars:
    hostname: "{{server_domain}}"
    with_tunnels: false
    xpla_job: 'XPlatform'
    xpla_version: '62'
    server_env: 'staging'
    server_cluster: 4
    server_port: 3000
    server_port2: 3100
  roles:
    - common
    - redis
    - mongodb
    - nodejs
    - xplatform
    - xplatform-main
    - xplatform-deploy
