---
- hosts: common
  roles:
    - common

- hosts: just_xplatform  
  vars:
    with_dashboard: false
    with_management: false
    node_env: 'box'
  roles:
    - common
    - mongodb
    - xplatform

- hosts: raspberry-provision
  gather_facts: no
  tasks:
    - name: Installing Python
      raw: apt-get install python-simplejson python-apt -y

- hosts: raspberry
  vars:
    with_dashboard: false
    with_management: true
    node_env: 'box'
  roles:
    - common
    - rasbpi
    - rasbpi-mongodb
    - xplatform
