---
- hosts: common
  roles:
    - common

- hosts: just_xplatform  
  vars:
    with_dashboard: false
    with_management: false
    node_env: 'box'
  roles:
    - common
    - mongodb
    - xplatform
    - xplatform-deploy

- hosts: raspberry-provision
  gather_facts: no
  tasks:
    - name: Installing Python
      raw: apt-get install python-simplejson python-apt -y

- hosts: raspberry
  vars:
    with_dashboard: false
    with_management: true
    server_env: 'box'
  roles:
    - common
    - rasbpi
    - rasbpi-mongodb
    - xplatform
    - xplatform-deploy

- hosts: xplatform-node
  vars:
    with_dashboard: false
    with_management: false
    server_env: 'staging'
    server_domain: 'test.local'
    server_short: 'test'
    server_cluster: 1
    server_port: 3000
    server_port2: 3001
    server_redis_url: 'redis://localhost:6379'
    server_mongo_url: 'mongodb://localhost:27017/platform-staging'
  roles:
    - common
    - xplatform
    - xplatform-deploy
